import { StyleSheet } from "react-native";
import { colors } from "../theme/colors";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  contentContainer: {
    flexGrow: 1,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 24,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 18,
    gap: 12,
  },
  headerContent: {
    flex: 1,
  },
  headerEyebrow: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    marginBottom: 4,
  },
  header: {
    color: colors.heading,
    fontSize: 28,
    fontWeight: "900",
    lineHeight: 34,
  },
  exitText: {
    color: colors.accent,
    fontSize: 14,
    fontWeight: "800",
    paddingTop: 6,
  },
  stepperCard: {
    backgroundColor: colors.card,
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  stepperTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
    gap: 12,
  },
  stepCount: {
    color: colors.heading,
    fontSize: 14,
    fontWeight: "900",
  },
  stepHint: {
    flex: 1,
    color: colors.subtext,
    fontSize: 12,
    textAlign: "right",
  },
  progressTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: "#FFE3CC",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: colors.accent,
  },
  card: {
    backgroundColor: colors.card,
    borderRadius: 20,
    padding: 18,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 14,
    elevation: 3,
  },
  cardTitle: {
    color: colors.heading,
    fontSize: 22,
    fontWeight: "900",
    marginBottom: 8,
    lineHeight: 28,
  },
  cardSubtitle: {
    color: colors.subtext,
    fontSize: 14,
    lineHeight: 21,
    marginBottom: 18,
  },
  choiceCard: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 16,
    minHeight: 92,
    marginBottom: 14,
    backgroundColor: "#FFFFFF",
  },
  choiceCardActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accentSoft,
  },
  choiceIcon: {
    width: 52,
    height: 52,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.accentSoft,
    marginRight: 14,
  },
  choiceIconActive: {
    backgroundColor: colors.accent,
  },
  choiceBody: {
    flex: 1,
    justifyContent: "center",
  },
  choiceTitle: {
    color: colors.heading,
    fontSize: 17,
    fontWeight: "900",
    marginBottom: 4,
  },
  choiceDesc: {
    color: colors.subtext,
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 8,
  },
  choiceBadge: {
    alignSelf: "flex-start",
    color: "#9A3412",
    backgroundColor: "#FFEDD5",
    borderRadius: 999,
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 5,
    fontSize: 12,
    fontWeight: "800",
  },
  infoCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "#FFF7ED",
    borderWidth: 1,
    borderColor: "#FED7AA",
    borderRadius: 16,
    padding: 16,
    marginTop: 6,
    gap: 10,
  },
  infoBody: {
    flex: 1,
  },
  infoTitle: {
    color: colors.heading,
    fontSize: 13,
    fontWeight: "900",
    marginBottom: 4,
  },
  infoText: {
    color: "#9A3412",
    fontSize: 12,
    lineHeight: 18,
  },
  label: {
    color: colors.heading,
    fontSize: 13,
    fontWeight: "800",
    marginTop: 12,
    marginBottom: 8,
  },
  inputWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 16,
    paddingHorizontal: 13,
    paddingVertical: 2,
    minHeight: 56,
  },
  inputWrapMultiline: {
    alignItems: "flex-start",
    paddingTop: 12,
    paddingBottom: 10,
  },
  input: {
    flex: 1,
    color: colors.text,
    fontSize: 14,
    paddingVertical: 14,
  },
  multilineInput: {
    minHeight: 72,
    textAlignVertical: "top",
    paddingTop: 2,
  },
  locationPinButton: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF7ED",
    borderWidth: 1,
    borderColor: "#FED7AA",
  },
  locationPinButtonActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  locationStatusText: {
    color: "#9A3412",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 8,
  },
  locationStatusTextActive: {
    color: colors.accent,
  },
  locationHelperText: {
    color: colors.subtext,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 4,
  },
  errorText: {
    color: colors.danger,
    fontSize: 12,
    fontWeight: "700",
    marginTop: 7,
  },
  chipsWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 12,
    marginBottom: 8,
  },
  chip: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "#FFFFFF",
  },
  chipActive: {
    backgroundColor: colors.accentSoft,
    borderColor: colors.accent,
  },
  chipText: {
    color: colors.subtext,
    fontSize: 12,
    fontWeight: "800",
  },
  chipTextActive: {
    color: colors.accent,
  },
  twoColumn: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: 4,
  },
  halfField: {
    width: "48.5%",
  },
  fullField: {
    width: "100%",
  },
  pickerButton: {
    minHeight: 56,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#F8FAFC",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  pickerText: {
    flex: 1,
    color: colors.text,
    fontSize: 13,
    fontWeight: "700",
  },
  placeholderText: {
    flex: 1,
    color: colors.muted,
    fontSize: 13,
    fontWeight: "600",
  },
  durationBox: {
    marginTop: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#F0FDF4",
    borderRadius: 14,
    padding: 14,
  },
  durationText: {
    color: "#166534",
    fontSize: 13,
    fontWeight: "800",
  },
  controlBlock: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
    backgroundColor: "#FFFFFF",
  },
  controlHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  controlTitle: {
    color: colors.heading,
    fontSize: 14,
    fontWeight: "900",
  },
  controlValue: {
    color: colors.accent,
    fontSize: 15,
    fontWeight: "900",
  },
  counterRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  circleButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.accent,
  },
  circleButtonText: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "900",
  },
  counterTrack: {
    flex: 1,
    height: 8,
    borderRadius: 999,
    backgroundColor: "#FFE3CC",
    overflow: "hidden",
  },
  counterFill: {
    height: "100%",
    backgroundColor: colors.accent,
  },
  compactGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 12,
  },
  compactOption: {
    width: 48,
    height: 44,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  compactOptionActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accentSoft,
  },
  compactOptionText: {
    color: colors.subtext,
    fontSize: 12,
    fontWeight: "900",
  },
  compactOptionTextActive: {
    color: colors.accent,
  },
  segmentRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 12,
  },
  segment: {
    flex: 1,
    minWidth: 92,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: "center",
    backgroundColor: "#FFFFFF",
  },
  segmentActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  segmentText: {
    color: colors.subtext,
    fontSize: 13,
    fontWeight: "900",
  },
  segmentTextActive: {
    color: "#FFFFFF",
  },
  purposeGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 14,
  },
  purposeOption: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 11,
    backgroundColor: "#FFFFFF",
  },
  purposeOptionActive: {
    backgroundColor: colors.accentSoft,
    borderColor: colors.accent,
  },
  purposeText: {
    color: colors.subtext,
    fontSize: 13,
    fontWeight: "800",
  },
  purposeTextActive: {
    color: colors.accent,
  },
  vehicleCard: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 18,
    overflow: "hidden",
    backgroundColor: "#FFFFFF",
    marginBottom: 16,
  },
  selectedVehicleCard: {
    flexDirection: "row",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 18,
    overflow: "hidden",
    backgroundColor: "#FFFFFF",
    marginBottom: 14,
  },
  directVehicleHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 14,
  },
  directVehicleHeaderText: {
    flex: 1,
  },
  changeVehicleButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#FDBA74",
    backgroundColor: "#FFF7ED",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  changeVehicleButtonText: {
    color: "#C2410C",
    fontSize: 12,
    fontWeight: "800",
  },
  selectedVehicleImage: {
    width: 118,
    minHeight: 118,
    backgroundColor: "#E5E7EB",
  },
  selectedVehicleImageFallback: {
    width: 118,
    minHeight: 118,
    backgroundColor: "#0B132B",
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
  },
  selectedVehicleImageFallbackText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "900",
    textAlign: "center",
  },
  selectedVehicleBody: {
    flex: 1,
    padding: 14,
    justifyContent: "center",
  },
  vehicleImage: {
    width: "100%",
    height: 160,
    backgroundColor: "#E5E7EB",
  },
  vehicleImageFallback: {
    width: "100%",
    height: 160,
    backgroundColor: "#0B132B",
    alignItems: "center",
    justifyContent: "center",
  },
  vehicleImageFallbackText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
  },
  vehicleBody: {
    padding: 16,
  },
  vehicleTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  vehicleName: {
    flex: 1,
    color: colors.heading,
    fontSize: 17,
    fontWeight: "900",
  },
  statusPill: {
    color: "#166534",
    backgroundColor: "#DCFCE7",
    borderRadius: 999,
    overflow: "hidden",
    paddingHorizontal: 9,
    paddingVertical: 5,
    fontSize: 11,
    fontWeight: "900",
  },
  vehicleMeta: {
    color: colors.subtext,
    fontSize: 13,
    marginTop: 6,
    lineHeight: 19,
  },
  vehicleRate: {
    color: colors.accent,
    fontSize: 16,
    fontWeight: "900",
    marginTop: 10,
    marginBottom: 12,
  },
  bookButton: {
    backgroundColor: colors.heading,
    borderRadius: 14,
    paddingVertical: 13,
    alignItems: "center",
  },
  bookButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
  },
  emptyCard: {
    backgroundColor: "#F8FAFC",
    borderRadius: 16,
    padding: 18,
  },
  emptyTitle: {
    color: colors.heading,
    fontSize: 15,
    fontWeight: "900",
    marginBottom: 4,
  },
  emptyText: {
    color: colors.subtext,
    fontSize: 13,
    lineHeight: 20,
  },
  summaryCard: {
    backgroundColor: "#F8FAFC",
    borderRadius: 16,
    padding: 14,
    marginBottom: 16,
  },
  summaryLabel: {
    color: colors.subtext,
    fontSize: 13,
    fontWeight: "700",
  },
  summaryValue: {
    color: colors.heading,
    fontSize: 15,
    fontWeight: "900",
  },
  reviewList: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    overflow: "hidden",
    marginBottom: 16,
  },
  reviewRow: {
    padding: 14,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  reviewLabel: {
    color: colors.subtext,
    fontSize: 12,
    fontWeight: "800",
    marginBottom: 4,
  },
  reviewValue: {
    color: colors.heading,
    fontSize: 14,
    fontWeight: "900",
    lineHeight: 20,
  },
  paymentSection: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
  },
  paymentOptionGrid: {
    gap: 10,
    marginBottom: 12,
  },
  paymentOptionCard: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  paymentOptionCardSelected: {
    borderColor: colors.accent,
    backgroundColor: colors.accentSoft,
  },
  paymentOptionText: {
    color: colors.heading,
    fontSize: 14,
    fontWeight: "900",
    marginBottom: 4,
  },
  paymentOptionTextSelected: {
    color: colors.accent,
  },
  paymentHelperText: {
    color: colors.subtext,
    fontSize: 12,
    lineHeight: 18,
  },
  termsBox: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    borderWidth: 1,
    borderColor: "#FED7AA",
    backgroundColor: "#FFF7ED",
    borderRadius: 16,
    padding: 14,
    marginBottom: 16,
  },
  termsText: {
    flex: 1,
    color: "#9A3412",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "700",
  },
  footer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 8,
  },
  inlineActionRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 4,
  },
  inlineActionRowStacked: {
    flexDirection: "column",
  },
  inlineActionButtonFull: {
    width: "100%",
    flex: 0,
  },
  bottomSpacer: {
    height: 24,
  },
  primaryButton: {
    flex: 1,
    backgroundColor: colors.accent,
    minHeight: 54,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
  },
  secondaryButton: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: colors.border,
    minHeight: 54,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryButtonText: {
    color: colors.heading,
    fontSize: 14,
    fontWeight: "900",
  },
  buttonDisabled: {
    opacity: 0.65,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15,23,42,0.55)",
    justifyContent: "flex-end",
  },
  reviewModal: {
    maxHeight: "92%",
    backgroundColor: colors.background,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    paddingHorizontal: 18,
    paddingTop: 18,
  },
  reviewScrollContent: {
    paddingBottom: 28,
  },
  modalClose: {
    alignItems: "center",
    paddingVertical: 16,
  },
  modalCloseText: {
    color: colors.accent,
    fontSize: 14,
    fontWeight: "900",
  },
  successIcon: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: "#16A34A",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  successTitle: {
    color: colors.heading,
    fontSize: 23,
    fontWeight: "900",
    marginBottom: 6,
  },
  successSubtitle: {
    color: colors.subtext,
    fontSize: 14,
    lineHeight: 21,
    marginBottom: 16,
  },
});
