import { StyleSheet } from "react-native";
import { colors } from "../theme/colors";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  contentContainer: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 40,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 14,
    gap: 12,
  },
  headerContent: {
    flex: 1,
  },
  header: {
    color: colors.heading,
    fontSize: 26,
    fontWeight: "700",
    lineHeight: 32,
  },
  exitText: {
    color: colors.accent,
    fontSize: 14,
    fontWeight: "600",
    paddingTop: 6,
  },
  stepperCard: {
    backgroundColor: colors.card,
    borderRadius: 16,
    padding: 14,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#E8EDF3",
  },
  stepperTop: {
    alignItems: "flex-start",
    marginBottom: 12,
    gap: 3,
  },
  stepCount: {
    color: colors.subtext,
    fontSize: 12,
    fontWeight: "500",
  },
  stepHint: {
    color: colors.heading,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "600",
  },
  progressTrack: {
    height: 4,
    borderRadius: 999,
    backgroundColor: "#FFE3CC",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: colors.accent,
  },
  card: {
    backgroundColor: colors.card,
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#E8EDF3",
  },
  cardTitle: {
    color: colors.heading,
    fontSize: 22,
    fontWeight: "700",
    marginBottom: 8,
    lineHeight: 28,
  },
  cardSubtitle: {
    color: colors.subtext,
    fontSize: 14,
    lineHeight: 21,
    marginBottom: 16,
  },
  choiceCard: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 14,
    minHeight: 84,
    marginBottom: 12,
    backgroundColor: "#FFFFFF",
  },
  choiceCardActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accentSoft,
  },
  choiceIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.accentSoft,
    marginRight: 14,
  },
  choiceIconActive: {
    backgroundColor: colors.accent,
  },
  choiceBody: {
    flex: 1,
    justifyContent: "center",
  },
  choiceTitle: {
    color: colors.heading,
    fontSize: 17,
    fontWeight: "600",
    marginBottom: 4,
  },
  choiceDesc: {
    color: colors.subtext,
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 8,
  },
  choiceBadge: {
    alignSelf: "flex-start",
    color: "#9A3412",
    backgroundColor: "#FFEDD5",
    borderRadius: 999,
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 5,
    fontSize: 12,
    fontWeight: "600",
  },
  infoCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "#FFF7ED",
    borderWidth: 1,
    borderColor: "#FED7AA",
    borderRadius: 16,
    padding: 16,
    marginTop: 6,
    gap: 10,
  },
  infoBody: {
    flex: 1,
  },
  infoTitle: {
    color: colors.heading,
    fontSize: 13,
    fontWeight: "600",
    marginBottom: 4,
  },
  infoText: {
    color: "#9A3412",
    fontSize: 12,
    lineHeight: 18,
  },
  label: {
    color: colors.heading,
    fontSize: 13,
    fontWeight: "600",
    marginTop: 12,
    marginBottom: 8,
  },
  inputWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 16,
    paddingHorizontal: 13,
    paddingVertical: 2,
    minHeight: 56,
  },
  inputWrapMultiline: {
    alignItems: "flex-start",
    paddingTop: 12,
    paddingBottom: 10,
  },
  input: {
    flex: 1,
    color: colors.text,
    fontSize: 14,
    paddingVertical: 14,
  },
  multilineInput: {
    minHeight: 72,
    textAlignVertical: "top",
    paddingTop: 2,
  },
  locationPinButton: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF7ED",
    borderWidth: 1,
    borderColor: "#FED7AA",
  },
  locationPinButtonActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  locationStatusText: {
    color: "#9A3412",
    fontSize: 12,
    fontWeight: "600",
    marginTop: 8,
  },
  locationStatusTextActive: {
    color: colors.accent,
  },
  locationHelperText: {
    color: colors.subtext,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 4,
  },
  locationHelperErrorText: {
    color: "#C2410C",
    fontSize: 12,
    lineHeight: 18,
    marginTop: 8,
    fontWeight: "600",
  },
  locationGuidanceText: {
    color: "#9A3412",
  },
  suggestionsCard: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    marginTop: 10,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.025,
    shadowRadius: 8,
    elevation: 1,
  },
  suggestionRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#EEF2F6",
  },
  suggestionTextWrap: {
    flex: 1,
  },
  suggestionTitle: {
    color: colors.heading,
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 18,
  },
  suggestionSubtitle: {
    color: colors.subtext,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 2,
  },
  suggestionFooter: {
    borderTopWidth: 1,
    borderTopColor: "#EEF2F6",
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: "#FFF7ED",
  },
  suggestionFooterText: {
    color: colors.subtext,
    fontSize: 11,
    lineHeight: 16,
    fontWeight: "600",
  },
  suggestionStateCard: {
    borderRadius: 14,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginTop: 10,
  },
  suggestionStateText: {
    color: colors.subtext,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "600",
  },
  errorText: {
    color: colors.danger,
    fontSize: 12,
    fontWeight: "600",
    marginTop: 7,
  },
  chipsWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 12,
    marginBottom: 8,
  },
  chip: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "#FFFFFF",
  },
  chipActive: {
    backgroundColor: colors.accentSoft,
    borderColor: colors.accent,
  },
  chipText: {
    color: colors.subtext,
    fontSize: 12,
    fontWeight: "600",
  },
  chipTextActive: {
    color: colors.accent,
  },
  twoColumn: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: 4,
  },
  halfField: {
    width: "48.5%",
  },
  fullField: {
    width: "100%",
  },
  pickerButton: {
    minHeight: 56,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#F8FAFC",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  pickerContent: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  pickerText: {
    flex: 1,
    color: colors.text,
    fontSize: 13,
    fontWeight: "600",
  },
  inputText: {
    flex: 1,
    color: colors.text,
    fontSize: 13,
    fontWeight: "500",
  },
  placeholderText: {
    flex: 1,
    color: colors.muted,
    fontSize: 13,
    fontWeight: "600",
  },
  dateFieldRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 4,
  },
  dateFieldCard: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 14,
  },
  dateFieldCardActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accentSoft,
  },
  calendarCard: {
    marginTop: 16,
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  calendarHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  calendarNavButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F8FAFC",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
  },
  calendarNavText: {
    color: colors.heading,
    fontSize: 20,
    fontWeight: "600",
    lineHeight: 24,
  },
  calendarMonthText: {
    color: colors.heading,
    fontSize: 16,
    fontWeight: "600",
  },
  calendarHint: {
    color: colors.subtext,
    fontSize: 13,
    lineHeight: 19,
    marginBottom: 12,
  },
  calendarWeekRow: {
    flexDirection: "row",
    marginBottom: 8,
  },
  calendarWeekLabel: {
    flex: 1,
    textAlign: "center",
    color: colors.subtext,
    fontSize: 12,
    fontWeight: "600",
  },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  calendarDay: {
    width: "13.4%",
    aspectRatio: 1,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "transparent",
    marginBottom: 6,
  },
  calendarDayMuted: {
    opacity: 0.55,
  },
  calendarDayDisabled: {
    opacity: 0.55,
  },
  calendarDayBlocked: {
    backgroundColor: "#FEE2E2",
    borderColor: "#FCA5A5",
  },
  calendarDayInRange: {
    backgroundColor: colors.accentSoft,
  },
  calendarDaySelected: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  calendarDayText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "600",
  },
  calendarDayTextMuted: {
    color: colors.subtext,
  },
  calendarDayTextBlocked: {
    color: colors.danger,
  },
  calendarDayTextSelected: {
    color: "#FFFFFF",
  },
  calendarBlockedDot: {
    position: "absolute",
    bottom: 7,
    width: 5,
    height: 5,
    borderRadius: 999,
    backgroundColor: colors.danger,
  },
  calendarLegendRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 14,
    marginTop: 12,
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  legendSwatch: {
    width: 12,
    height: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "#FFFFFF",
  },
  legendSwatchSelected: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  legendSwatchRange: {
    backgroundColor: colors.accentSoft,
    borderColor: colors.accentSoft,
  },
  legendSwatchBlocked: {
    backgroundColor: "#FEE2E2",
    borderColor: "#FCA5A5",
  },
  legendText: {
    color: colors.subtext,
    fontSize: 12,
    fontWeight: "600",
  },
  durationBox: {
    marginTop: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#F0FDF4",
    borderRadius: 14,
    padding: 14,
  },
  durationBoxError: {
    backgroundColor: "#FEF2F2",
  },
  durationBoxNeutral: {
    backgroundColor: "#F8FAFC",
  },
  durationText: {
    color: "#166534",
    fontSize: 13,
    fontWeight: "600",
  },
  durationTextError: {
    color: "#B91C1C",
  },
  durationTextNeutral: {
    color: "#334155",
  },
  inlineNoticeInfo: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    marginTop: 12,
    padding: 14,
    borderRadius: 14,
    backgroundColor: "#EFF6FF",
    borderWidth: 1,
    borderColor: "#BFDBFE",
  },
  inlineNoticeInfoText: {
    flex: 1,
    color: "#1D4ED8",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "600",
  },
  inlineNoticeWarning: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    marginTop: 12,
    padding: 14,
    borderRadius: 14,
    backgroundColor: "#FFF7ED",
    borderWidth: 1,
    borderColor: "#FED7AA",
  },
  inlineNoticeWarningText: {
    flex: 1,
    color: "#9A3412",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "600",
  },
  inlineNoticeError: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    marginTop: 12,
    padding: 14,
    borderRadius: 14,
    backgroundColor: "#FEF2F2",
    borderWidth: 1,
    borderColor: "#FECACA",
  },
  inlineNoticeErrorText: {
    flex: 1,
    color: "#B91C1C",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "600",
  },
  inlineNoticeSuccess: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    marginTop: 12,
    padding: 14,
    borderRadius: 14,
    backgroundColor: "#F0FDF4",
    borderWidth: 1,
    borderColor: "#BBF7D0",
  },
  inlineNoticeSuccessText: {
    flex: 1,
    color: "#166534",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "600",
  },
  controlBlock: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
    backgroundColor: "#FFFFFF",
  },
  controlHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  controlTitle: {
    color: colors.heading,
    fontSize: 14,
    fontWeight: "600",
  },
  controlValue: {
    color: colors.accent,
    fontSize: 15,
    fontWeight: "600",
  },
  counterRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  circleButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.accent,
  },
  circleButtonText: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "600",
  },
  counterTrack: {
    flex: 1,
    height: 8,
    borderRadius: 999,
    backgroundColor: "#FFE3CC",
    overflow: "hidden",
  },
  counterFill: {
    height: "100%",
    backgroundColor: colors.accent,
  },
  compactGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 12,
  },
  compactOption: {
    width: 48,
    height: 44,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  compactOptionActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accentSoft,
  },
  compactOptionText: {
    color: colors.subtext,
    fontSize: 12,
    fontWeight: "600",
  },
  compactOptionTextActive: {
    color: colors.accent,
  },
  segmentRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 12,
  },
  pickupModeOptions: {
    gap: 12,
    marginBottom: 10,
  },
  pickupModeCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 14,
    backgroundColor: "#FFFFFF",
  },
  pickupModeCardActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accentSoft,
  },
  pickupModeIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF7ED",
    borderWidth: 1,
    borderColor: "#FED7AA",
  },
  pickupModeIconActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  pickupModeBody: {
    flex: 1,
  },
  pickupModeTitle: {
    color: colors.heading,
    fontSize: 15,
    fontWeight: "600",
    lineHeight: 20,
    marginBottom: 4,
  },
  pickupModeTitleActive: {
    color: "#9A3412",
  },
  pickupModeDescription: {
    color: colors.subtext,
    fontSize: 12,
    lineHeight: 18,
  },
  pickupModeDescriptionActive: {
    color: "#9A3412",
  },
  segment: {
    flex: 1,
    minWidth: 92,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: "center",
    backgroundColor: "#FFFFFF",
  },
  segmentActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  segmentText: {
    color: colors.subtext,
    fontSize: 13,
    fontWeight: "600",
  },
  segmentTextActive: {
    color: "#FFFFFF",
  },
  purposeGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 14,
  },
  purposeOption: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 11,
    backgroundColor: "#FFFFFF",
  },
  purposeOptionActive: {
    backgroundColor: colors.accentSoft,
    borderColor: colors.accent,
  },
  purposeText: {
    color: colors.subtext,
    fontSize: 13,
    fontWeight: "600",
  },
  purposeTextActive: {
    color: colors.accent,
  },
  vehicleCard: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 18,
    overflow: "hidden",
    backgroundColor: "#FFFFFF",
    marginBottom: 16,
  },
  selectedVehicleCard: {
    flexDirection: "row",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: "#FFFFFF",
    marginBottom: 0,
  },
  directVehicleHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 14,
  },
  directVehicleHeaderText: {
    flex: 1,
  },
  changeVehicleButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#FDBA74",
    backgroundColor: "#FFF7ED",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  changeVehicleButtonText: {
    color: "#C2410C",
    fontSize: 12,
    fontWeight: "600",
  },
  selectedVehicleImage: {
    width: 92,
    minHeight: 104,
    backgroundColor: "#E5E7EB",
  },
  selectedVehicleImageFallback: {
    width: 92,
    minHeight: 104,
    backgroundColor: "#0B132B",
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
  },
  selectedVehicleImageFallbackText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "600",
    textAlign: "center",
  },
  selectedVehicleBody: {
    flex: 1,
    padding: 12,
    justifyContent: "center",
  },
  vehicleImage: {
    width: "100%",
    height: 160,
    backgroundColor: "#E5E7EB",
  },
  vehicleImageFallback: {
    width: "100%",
    height: 160,
    backgroundColor: "#0B132B",
    alignItems: "center",
    justifyContent: "center",
  },
  vehicleImageFallbackText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  vehicleBody: {
    padding: 16,
  },
  vehicleTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  vehicleName: {
    flex: 1,
    color: colors.heading,
    fontSize: 17,
    fontWeight: "600",
  },
  statusPill: {
    color: "#166534",
    backgroundColor: "#DCFCE7",
    borderRadius: 999,
    overflow: "hidden",
    paddingHorizontal: 9,
    paddingVertical: 5,
    fontSize: 11,
    fontWeight: "600",
  },
  vehicleMeta: {
    color: colors.subtext,
    fontSize: 13,
    marginTop: 6,
    lineHeight: 19,
  },
  vehicleRate: {
    color: colors.accent,
    fontSize: 16,
    fontWeight: "600",
    marginTop: 8,
    marginBottom: 0,
  },
  vehicleFitCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#F8FAFC",
    padding: 12,
    marginTop: 10,
    marginBottom: 4,
  },
  vehicleFitPrimary: {
    color: colors.heading,
    fontSize: 12,
    fontWeight: "600",
    lineHeight: 18,
  },
  vehicleFitSecondary: {
    color: colors.subtext,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 2,
  },
  bookButton: {
    backgroundColor: colors.heading,
    borderRadius: 14,
    paddingVertical: 13,
    alignItems: "center",
  },
  bookButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  emptyCard: {
    backgroundColor: "#F8FAFC",
    borderRadius: 16,
    padding: 18,
  },
  emptyTitle: {
    color: colors.heading,
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 4,
  },
  emptyText: {
    color: colors.subtext,
    fontSize: 13,
    lineHeight: 20,
  },
  summaryCard: {
    backgroundColor: "#F8FAFC",
    borderRadius: 16,
    padding: 14,
    marginBottom: 16,
  },
  summaryLabel: {
    color: colors.subtext,
    fontSize: 13,
    fontWeight: "600",
  },
  summaryValue: {
    color: colors.heading,
    fontSize: 15,
    fontWeight: "600",
  },
  reviewPage: {
    marginBottom: 4,
  },
  reviewIntro: {
    marginBottom: 2,
  },
  reviewSection: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E8EDF3",
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
  },
  reviewSectionTitle: {
    color: colors.heading,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "600",
    marginBottom: 10,
  },
  reviewSectionHelper: {
    color: colors.subtext,
    fontSize: 13,
    lineHeight: 19,
    marginTop: -4,
    marginBottom: 14,
  },
  reviewSubsection: {
    marginTop: 16,
  },
  reviewGroupTitle: {
    color: colors.heading,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "600",
    marginBottom: 8,
  },
  reviewGuidance: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  reviewGuidanceText: {
    flex: 1,
    color: colors.subtext,
    fontSize: 12,
    lineHeight: 18,
  },
  reviewList: {
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  reviewRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 16,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  reviewRowLast: {
    borderBottomWidth: 0,
  },
  reviewLabel: {
    width: 104,
    flexShrink: 0,
    color: colors.subtext,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "500",
  },
  reviewValue: {
    flex: 1,
    flexShrink: 1,
    color: colors.heading,
    fontSize: 13,
    fontWeight: "500",
    lineHeight: 19,
    textAlign: "right",
  },
  paymentOptionGrid: {
    gap: 8,
    marginBottom: 14,
  },
  paymentOptionCard: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 12,
    minHeight: 56,
    justifyContent: "center",
  },
  paymentOptionCardSelected: {
    borderColor: colors.accent,
    backgroundColor: colors.accentSoft,
  },
  paymentOptionText: {
    color: colors.heading,
    fontSize: 14,
    fontWeight: "600",
  },
  paymentOptionTextSelected: {
    color: colors.accent,
  },
  reviewOptionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
  },
  reviewOptionTitle: {
    flex: 1,
  },
  reviewOptionDescription: {
    color: colors.subtext,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 5,
    paddingLeft: 29,
  },
  disclosureGroup: {
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 14,
    marginTop: 2,
  },
  presetRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 10,
  },
  presetButton: {
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "#F8FAFC",
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  presetButtonText: {
    color: colors.heading,
    fontSize: 12,
    fontWeight: "600",
  },
  promoSection: {
    marginTop: 4,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  promoLabel: {
    color: colors.heading,
    fontSize: 13,
    fontWeight: "500",
    marginBottom: 8,
  },
  promoRow: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  promoRowStacked: {
    flexDirection: "column",
    alignItems: "stretch",
  },
  promoInputWrap: {
    flex: 1,
    minHeight: 48,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#F8FAFC",
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  promoInputWrapFull: {
    width: "100%",
    flex: 0,
  },
  promoInput: {
    flex: 1,
    color: colors.text,
    fontSize: 13,
    paddingVertical: 12,
  },
  promoApplyButton: {
    minHeight: 48,
    borderRadius: 14,
    backgroundColor: colors.accent,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  promoApplyButtonFull: {
    width: "100%",
  },
  promoApplyButtonText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "600",
  },
  promoHelperText: {
    color: colors.subtext,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 8,
  },
  promoHelperTextError: {
    color: colors.danger,
  },
  promoHelperTextSuccess: {
    color: "#166534",
  },
  priceSummary: {
    borderRadius: 14,
    backgroundColor: "#F8FAFC",
    paddingHorizontal: 12,
  },
  priceRow: {
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  priceRowTotal: {
    minHeight: 54,
    borderTopWidth: 0,
  },
  priceLabel: {
    flex: 1,
    color: colors.subtext,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "500",
  },
  priceValue: {
    flexShrink: 0,
    color: colors.heading,
    fontSize: 14,
    fontWeight: "600",
  },
  priceValueTotal: {
    flexShrink: 0,
    color: colors.accent,
    fontSize: 18,
    fontWeight: "700",
  },
  termsBox: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    borderWidth: 1,
    borderColor: "#FED7AA",
    backgroundColor: "#FFF7ED",
    borderRadius: 16,
    padding: 14,
    marginBottom: 16,
  },
  termsText: {
    flex: 1,
    color: "#9A3412",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "500",
  },
  footer: {
    flexDirection: "column",
    gap: 10,
    marginTop: 8,
  },
  reviewEditButton: {
    width: "100%",
    flex: 0,
  },
  reviewSubmitButton: {
    width: "100%",
    flex: 0,
  },
  inlineActionRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 4,
  },
  inlineActionRowStacked: {
    flexDirection: "column",
  },
  inlineActionButtonFull: {
    width: "100%",
    flex: 0,
  },
  bottomSpacer: {
    height: 56,
  },
  primaryButton: {
    flex: 1,
    backgroundColor: colors.accent,
    minHeight: 54,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  secondaryButton: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: colors.border,
    minHeight: 54,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryButtonText: {
    color: colors.heading,
    fontSize: 14,
    fontWeight: "600",
  },
  buttonDisabled: {
    opacity: 0.65,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15,23,42,0.55)",
    justifyContent: "flex-end",
  },
  optionPickerSheet: {
    backgroundColor: colors.background,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 28,
    gap: 14,
  },
  optionPickerHandle: {
    alignSelf: "center",
    width: 52,
    height: 6,
    borderRadius: 999,
    backgroundColor: "#D0D5DD",
  },
  optionPickerTitle: {
    color: colors.heading,
    fontSize: 22,
    fontWeight: "700",
  },
  optionPickerSubtitle: {
    color: colors.subtext,
    fontSize: 14,
    lineHeight: 21,
  },
  optionPickerList: {
    gap: 10,
  },
  optionPickerItem: {
    minHeight: 54,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 14,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  optionPickerItemSelected: {
    borderColor: colors.accent,
    backgroundColor: colors.accentSoft,
  },
  optionPickerItemText: {
    flex: 1,
    color: colors.heading,
    fontSize: 14,
    fontWeight: "600",
  },
  optionPickerItemTextSelected: {
    color: colors.accent,
  },
  successIcon: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: "#16A34A",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  successTitle: {
    color: colors.heading,
    fontSize: 23,
    fontWeight: "700",
    marginBottom: 6,
  },
  successSubtitle: {
    color: colors.subtext,
    fontSize: 14,
    lineHeight: 21,
    marginBottom: 16,
  },
});
