import { StyleSheet } from "react-native";
import { colors } from "../theme/colors";

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(15,23,42,0.55)",
    justifyContent: "flex-end",
  },
  sheet: {
    maxHeight: "88%",
    backgroundColor: colors.background,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 18,
    paddingTop: 14,
  },
  content: {
    paddingBottom: 28,
  },
  handle: {
    width: 56,
    height: 5,
    borderRadius: 999,
    backgroundColor: "#D0D5DD",
    alignSelf: "center",
    marginBottom: 16,
  },
  title: {
    color: colors.heading,
    fontSize: 22,
    fontWeight: "900",
    marginBottom: 8,
  },
  subtitle: {
    color: colors.subtext,
    fontSize: 13,
    lineHeight: 20,
    marginBottom: 16,
  },
  mapPreviewCard: {
    borderRadius: 22,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    padding: 14,
    marginBottom: 14,
  },
  mapGrid: {
    height: 280,
    borderRadius: 18,
    overflow: "hidden",
    backgroundColor: "#EEF2F6",
    position: "relative",
  },
  map: {
    width: "100%",
    height: "100%",
  },
  previewCard: {
    borderRadius: 18,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: colors.border,
    padding: 14,
    marginBottom: 12,
  },
  previewLabel: {
    color: colors.subtext,
    fontSize: 12,
    fontWeight: "800",
    marginBottom: 6,
  },
  previewValue: {
    color: colors.heading,
    fontSize: 14,
    fontWeight: "900",
  },
  labelInput: {
    minHeight: 48,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#F8FAFC",
    color: colors.text,
    paddingHorizontal: 14,
    fontSize: 13,
    fontWeight: "700",
  },
  helperCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    borderRadius: 16,
    backgroundColor: "#FFF7ED",
    borderWidth: 1,
    borderColor: "#FED7AA",
    padding: 14,
    marginBottom: 16,
  },
  helperText: {
    flex: 1,
    color: "#9A3412",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "700",
  },
  errorCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    borderRadius: 16,
    backgroundColor: "#FEF2F2",
    borderWidth: 1,
    borderColor: "#FECACA",
    padding: 14,
    marginBottom: 16,
  },
  errorText: {
    flex: 1,
    color: "#991B1B",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "700",
  },
  footer: {
    flexDirection: "row",
    gap: 12,
  },
  primaryButton: {
    flex: 1,
    minHeight: 52,
    borderRadius: 16,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
  },
  secondaryButton: {
    flex: 1,
    minHeight: 52,
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryButtonText: {
    color: colors.heading,
    fontSize: 14,
    fontWeight: "900",
  },
});
