import { Platform, StyleSheet } from "react-native";
import { colors } from "../theme/colors";

const shadow = Platform.select({
  ios: {
    shadowColor: "#0B132B",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 18,
  },
  android: {
    elevation: 4,
  },
  default: {
    shadowColor: "#0B132B",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
  },
});

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: "#F5F6F8",
  },
  screen: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  content: {
    paddingBottom: 34,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  headerContent: {
    flex: 1,
  },
  title: {
    color: "#0B132B",
    fontSize: 22,
    fontWeight: "900",
  },
  subtitle: {
    color: "#6B7280",
    fontSize: 13,
    fontWeight: "700",
    marginTop: 2,
  },
  statusCard: {
    backgroundColor: "#0B132B",
    borderRadius: 24,
    padding: 18,
    marginBottom: 14,
    ...shadow,
  },
  statusTitle: {
    color: "#FFFFFF",
    fontSize: 19,
    fontWeight: "900",
    marginBottom: 6,
  },
  statusBody: {
    color: "#F8FAFC",
    fontSize: 14,
    lineHeight: 21,
    fontWeight: "700",
  },
  statusHelper: {
    color: "#CBD5E1",
    fontSize: 12,
    lineHeight: 18,
    marginTop: 6,
    fontWeight: "700",
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    padding: 16,
    marginBottom: 14,
    ...shadow,
  },
  sectionTitle: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "900",
    marginBottom: 12,
  },
  loadingBox: {
    minHeight: 100,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  loadingText: {
    color: colors.subtext,
    fontSize: 12,
    fontWeight: "700",
  },
  qrCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#FED7AA",
    backgroundColor: "#FFF7ED",
    alignItems: "center",
    padding: 16,
  },
  qrImage: {
    width: 220,
    height: 220,
    maxWidth: "100%",
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
  },
  qrHint: {
    color: "#C2410C",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 10,
  },
  placeholderCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#F8FAFC",
    padding: 16,
  },
  placeholderText: {
    color: colors.subtext,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "700",
  },
  detailCard: {
    borderRadius: 16,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    padding: 14,
    marginBottom: 10,
  },
  detailLabel: {
    color: "#64748B",
    fontSize: 11,
    fontWeight: "800",
    marginBottom: 5,
  },
  detailValue: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "900",
  },
  infoCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#FED7AA",
    backgroundColor: "#FFF7ED",
    padding: 16,
    marginBottom: 14,
    gap: 10,
  },
  infoText: {
    color: "#9A3412",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "700",
  },
  contractStatusPill: {
    alignSelf: "flex-start",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginBottom: 10,
  },
  contractStatusPillPending: {
    backgroundColor: "#FFF4E8",
    borderWidth: 1,
    borderColor: "#FED7AA",
  },
  contractStatusPillAccepted: {
    backgroundColor: "#DCFCE7",
    borderWidth: 1,
    borderColor: "#BBF7D0",
  },
  contractStatusText: {
    fontSize: 12,
    fontWeight: "900",
  },
  contractStatusTextPending: {
    color: "#C2410C",
  },
  contractStatusTextAccepted: {
    color: "#166534",
  },
  contractBodyText: {
    color: "#111827",
    fontSize: 13,
    lineHeight: 20,
    fontWeight: "700",
  },
  contractHelperText: {
    color: "#64748B",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "700",
    marginTop: 6,
  },
  inlineErrorText: {
    color: "#B42318",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "700",
    marginTop: 8,
    marginBottom: 6,
  },
  contractGateCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#FED7AA",
    backgroundColor: "#FFF7ED",
    padding: 14,
    marginBottom: 12,
  },
  contractGateText: {
    color: "#9A3412",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "800",
  },
  contractGateSubtext: {
    color: "#C2410C",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "700",
    marginTop: 6,
  },
  assetName: {
    color: "#64748B",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 10,
    marginBottom: 8,
  },
  proofPreviewCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#FED7AA",
    backgroundColor: "#FFF7ED",
    padding: 12,
    marginBottom: 12,
  },
  proofPreviewImage: {
    width: "100%",
    height: 220,
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
  },
  proofActionRow: {
    flexDirection: "row",
    gap: 10,
  },
  proofActionButton: {
    flex: 1,
    marginBottom: 0,
  },
  primaryButton: {
    minHeight: 52,
    borderRadius: 16,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
  },
  secondaryButton: {
    minHeight: 50,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#FED7AA",
    backgroundColor: "#FFF4E8",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  secondaryButtonText: {
    color: "#C2410C",
    fontSize: 14,
    fontWeight: "900",
  },
  buttonDisabled: {
    opacity: 0.65,
  },
  previewOverlay: {
    flex: 1,
    backgroundColor: "rgba(15,23,42,0.75)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  previewCard: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 20,
  },
  previewTitle: {
    color: "#111827",
    fontSize: 18,
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 4,
  },
  previewSubtitle: {
    color: "#64748B",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
    marginBottom: 12,
  },
  previewImage: {
    width: "100%",
    height: 320,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15,23,42,0.5)",
    justifyContent: "center",
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  contractModalCard: {
    maxHeight: "92%",
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 18,
  },
  contractModalHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  contractModalTitle: {
    color: "#0B132B",
    fontSize: 18,
    fontWeight: "900",
  },
  contractModalSubtitle: {
    color: "#64748B",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 4,
  },
  modalCloseButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 12,
  },
  contractScroll: {
    maxHeight: 280,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#F8FAFC",
  },
  contractScrollContent: {
    padding: 14,
  },
  contractText: {
    color: "#1F2937",
    fontSize: 13,
    lineHeight: 20,
    fontWeight: "600",
  },
  checkboxRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginTop: 12,
    marginBottom: 12,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: "#D0D5DD",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
    marginTop: 2,
  },
  checkboxChecked: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  checkboxText: {
    flex: 1,
    color: "#111827",
    fontSize: 13,
    lineHeight: 20,
    fontWeight: "700",
  },
  signatureInput: {
    minHeight: 50,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#D0D5DD",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: "#111827",
    fontSize: 14,
    fontWeight: "700",
    marginBottom: 12,
  },
  contractAcceptedCard: {
    marginTop: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#BBF7D0",
    backgroundColor: "#F0FDF4",
    padding: 14,
  },
  contractAcceptedText: {
    color: "#166534",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "900",
  },
  contractAcceptedSubtext: {
    color: "#15803D",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "700",
    marginTop: 6,
  },
});
