import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#f8fafc",
  },
  container: {
    flex: 1,
    backgroundColor: "#f8fafc",
  },
  contentContainer: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 32,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 18,
    gap: 12,
  },
  headerButton: {
    width: 40,
    height: 40,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  headerTextWrap: {
    flex: 1,
  },
  title: {
    fontSize: 24,
    fontWeight: "900",
    color: "#0f172a",
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: "#64748b",
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  highlightCard: {
    borderWidth: 1,
    borderColor: "#e2e8f0",
    backgroundColor: "#ffffff",
  },
  cardTitle: {
    fontSize: 17,
    fontWeight: "900",
    color: "#111827",
    marginBottom: 6,
  },
  cardSubtitle: {
    fontSize: 13,
    lineHeight: 19,
    color: "#64748b",
    marginBottom: 14,
  },
  statusTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
    marginBottom: 14,
  },
  badge: {
    alignSelf: "flex-start",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  badgeNeutral: {
    backgroundColor: "#e2e8f0",
  },
  badgeWarning: {
    backgroundColor: "#ffedd5",
  },
  badgeInfo: {
    backgroundColor: "#dbeafe",
  },
  badgeSuccess: {
    backgroundColor: "#dcfce7",
  },
  badgeDanger: {
    backgroundColor: "#fee2e2",
  },
  badgeText: {
    fontSize: 12,
    fontWeight: "800",
  },
  badgeTextNeutral: {
    color: "#475569",
  },
  badgeTextWarning: {
    color: "#c2410c",
  },
  badgeTextInfo: {
    color: "#1d4ed8",
  },
  badgeTextSuccess: {
    color: "#15803d",
  },
  badgeTextDanger: {
    color: "#b91c1c",
  },
  summaryGrid: {
    gap: 12,
  },
  summaryRow: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 16,
    padding: 14,
    backgroundColor: "#f8fafc",
  },
  summaryLabel: {
    fontSize: 12,
    fontWeight: "800",
    color: "#64748b",
    marginBottom: 6,
  },
  summaryValue: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "800",
    color: "#0f172a",
  },
  levelRow: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 16,
    padding: 14,
    backgroundColor: "#f8fafc",
    marginBottom: 14,
  },
  levelValue: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "900",
    color: "#0f172a",
  },
  summarySubvalue: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
    color: "#475569",
    marginTop: 6,
  },
  eligibilityRow: {
    flexDirection: "row",
    gap: 10,
  },
  eligibilityCard: {
    flex: 1,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    padding: 16,
    backgroundColor: "#f8fafc",
  },
  eligibilityCardActive: {
    borderColor: "#fdba74",
    backgroundColor: "#fff7ed",
  },
  eligibilityCardSelected: {
    borderColor: "#f97316",
    borderWidth: 2,
    backgroundColor: "#fff7ed",
  },
  eligibilityLabel: {
    fontSize: 13,
    color: "#64748b",
    fontWeight: "700",
    marginBottom: 8,
  },
  eligibilityValue: {
    fontSize: 15,
    fontWeight: "900",
    color: "#111827",
  },
  checklistRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: 10,
  },
  checklistLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  checklistTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#111827",
  },
  checklistSubtitle: {
    fontSize: 12,
    color: "#64748b",
    marginTop: 2,
  },
  segmentRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 16,
  },
  segmentButton: {
    flex: 1,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    paddingVertical: 14,
    paddingHorizontal: 14,
    backgroundColor: "#ffffff",
  },
  segmentButtonActive: {
    borderColor: "#f97316",
    backgroundColor: "#fff7ed",
  },
  segmentTitle: {
    fontSize: 14,
    fontWeight: "900",
    color: "#111827",
    marginBottom: 4,
  },
  segmentText: {
    fontSize: 12,
    lineHeight: 18,
    color: "#64748b",
  },
  segmentTextActive: {
    color: "#9a3412",
  },
  sectionHeader: {
    fontSize: 15,
    fontWeight: "900",
    color: "#111827",
    marginBottom: 10,
  },
  uploadGroup: {
    marginBottom: 16,
  },
  uploadGroupTitle: {
    fontSize: 14,
    fontWeight: "900",
    color: "#111827",
    marginBottom: 4,
  },
  uploadGroupSubtitle: {
    fontSize: 12,
    lineHeight: 18,
    color: "#64748b",
    marginBottom: 12,
  },
  uploadGrid: {
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
  },
  uploadCard: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 18,
    backgroundColor: "#ffffff",
    overflow: "hidden",
  },
  uploadPreview: {
    width: "100%",
    height: 170,
    backgroundColor: "#f1f5f9",
  },
  uploadPlaceholder: {
    width: "100%",
    height: 170,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f8fafc",
    paddingHorizontal: 18,
  },
  uploadPlaceholderText: {
    fontSize: 13,
    color: "#64748b",
    fontWeight: "700",
    marginTop: 10,
    textAlign: "center",
  },
  uploadBody: {
    padding: 14,
  },
  uploadTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
    marginBottom: 10,
  },
  uploadTitle: {
    fontSize: 14,
    fontWeight: "900",
    color: "#111827",
    marginBottom: 4,
  },
  uploadHint: {
    fontSize: 12,
    lineHeight: 18,
    color: "#64748b",
  },
  slotRemark: {
    fontSize: 12,
    lineHeight: 18,
    color: "#b45309",
    marginBottom: 10,
    fontWeight: "700",
  },
  draftNotice: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
    backgroundColor: "#eff6ff",
    borderWidth: 1,
    borderColor: "#bfdbfe",
  },
  draftNoticeText: {
    flex: 1,
    color: "#1d4ed8",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "800",
  },
  draftSummaryNotice: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    backgroundColor: "#eff6ff",
    borderWidth: 1,
    borderColor: "#bfdbfe",
  },
  draftSummaryNoticeText: {
    flex: 1,
    color: "#1e40af",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "700",
  },
  selfieButtonWrap: {
    alignItems: "center",
    marginBottom: 10,
  },
  selfieActionButton: {
    width: "72%",
    flexGrow: 0,
  },
  uploadActions: {
    flexDirection: "row",
    gap: 10,
  },
  uploadActionButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  uploadPrimary: {
    backgroundColor: "#f97316",
  },
  uploadSecondary: {
    backgroundColor: "#fff7ed",
    borderWidth: 1,
    borderColor: "#fdba74",
  },
  uploadDanger: {
    backgroundColor: "#fff1f2",
    borderWidth: 1,
    borderColor: "#fecdd3",
  },
  uploadPrimaryText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "800",
  },
  uploadSecondaryText: {
    color: "#c2410c",
    fontSize: 13,
    fontWeight: "800",
  },
  uploadDangerText: {
    color: "#be123c",
    fontSize: 13,
    fontWeight: "800",
  },
  slotHelperText: {
    fontSize: 12,
    lineHeight: 18,
    color: "#64748b",
    marginTop: 10,
  },
  slotErrorText: {
    fontSize: 12,
    lineHeight: 18,
    color: "#dc2626",
    fontWeight: "700",
    marginTop: 10,
  },
  groupActionPanel: {
    gap: 12,
    borderRadius: 16,
    padding: 14,
    marginTop: 16,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  groupActionPanelPending: {
    backgroundColor: "#eff6ff",
    borderColor: "#93c5fd",
  },
  groupActionMessage: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  groupActionMessageBody: {
    flex: 1,
  },
  groupActionTitle: {
    color: "#1e3a8a",
    fontSize: 15,
    fontWeight: "900",
    marginBottom: 4,
  },
  groupActionText: {
    color: "#475569",
    fontSize: 13,
    lineHeight: 19,
  },
  groupActionServerStatus: {
    color: "#1d4ed8",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "800",
    marginTop: 4,
  },
  groupActionRequirement: {
    color: "#b45309",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "700",
    textAlign: "center",
  },
  groupActionError: {
    color: "#b91c1c",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "800",
    textAlign: "center",
  },
  noticeCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    backgroundColor: "#fff7ed",
    borderWidth: 1,
    borderColor: "#fed7aa",
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
  },
  noticeCardDanger: {
    backgroundColor: "#fef2f2",
    borderColor: "#fecaca",
  },
  noticeCardWarning: {
    backgroundColor: "#fff7ed",
    borderColor: "#fed7aa",
  },
  noticeCardSuccess: {
    backgroundColor: "#f0fdf4",
    borderColor: "#bbf7d0",
  },
  noticeText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 19,
    color: "#9a3412",
  },
  noticeTextDanger: {
    color: "#b91c1c",
  },
  noticeTextWarning: {
    color: "#9a3412",
  },
  noticeTextSuccess: {
    color: "#166534",
  },
  errorText: {
    fontSize: 13,
    lineHeight: 19,
    color: "#dc2626",
    fontWeight: "700",
    marginBottom: 12,
  },
  submitButton: {
    minHeight: 54,
    borderRadius: 16,
    backgroundColor: "#f97316",
    alignItems: "center",
    justifyContent: "center",
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  submitButtonText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "900",
  },
  submitButtonBusyContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  compactGroupSummary: {
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#e2e8f0",
    marginBottom: 14,
  },
  compactSummaryRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 18,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
  },
  compactSummaryRowLast: {
    borderBottomWidth: 0,
  },
  compactSummaryLabel: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: "700",
  },
  compactSummaryValueWrap: {
    flex: 1,
    alignItems: "flex-end",
  },
  compactSummaryValue: {
    flexShrink: 1,
    color: "#0f172a",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "800",
    textAlign: "right",
  },
  compactSummaryDetail: {
    color: "#64748b",
    fontSize: 11,
    lineHeight: 16,
    textAlign: "right",
    marginTop: 2,
  },
  captureRow: {
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  captureRowHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 10,
  },
  captureRowTitle: {
    flex: 1,
    color: "#0f172a",
    fontSize: 15,
    fontWeight: "800",
  },
  requiredMark: {
    color: "#dc2626",
  },
  exampleLink: {
    color: "#2563eb",
    fontSize: 13,
    fontWeight: "800",
  },
  captureRowContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  captureThumbnail: {
    width: 94,
    height: 70,
    borderRadius: 10,
    backgroundColor: "#f1f5f9",
  },
  captureThumbnailEmpty: {
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderStyle: "dashed",
  },
  captureRowBody: {
    flex: 1,
    alignItems: "flex-start",
  },
  captureStatusBadge: {
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  captureRowHint: {
    color: "#64748b",
    fontSize: 12,
    lineHeight: 17,
    marginTop: 6,
  },
  inlineDraftNotice: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginTop: 6,
  },
  inlineDraftNoticeText: {
    color: "#1d4ed8",
    fontSize: 12,
    fontWeight: "800",
  },
  captureRowActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 12,
  },
  compactPrimaryAction: {
    minHeight: 40,
    borderRadius: 10,
    paddingHorizontal: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f97316",
  },
  compactPrimaryActionText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "800",
  },
  compactSecondaryAction: {
    minHeight: 40,
    borderRadius: 10,
    paddingHorizontal: 18,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#cbd5e1",
    backgroundColor: "#ffffff",
  },
  compactSecondaryActionText: {
    color: "#334155",
    fontSize: 13,
    fontWeight: "800",
  },
  compactDangerAction: {
    minHeight: 40,
    borderRadius: 10,
    paddingHorizontal: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  compactDangerActionText: {
    color: "#be123c",
    fontSize: 12,
    fontWeight: "800",
  },
  exampleModalBackdrop: {
    flex: 1,
    justifyContent: "center",
    padding: 20,
    backgroundColor: "rgba(15, 23, 42, 0.62)",
  },
  exampleModalCard: {
    borderRadius: 20,
    padding: 20,
    backgroundColor: "#ffffff",
  },
  exampleModalHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  exampleModalTitle: {
    color: "#0f172a",
    fontSize: 20,
    fontWeight: "900",
    textTransform: "capitalize",
  },
  exampleModalSubtitle: {
    color: "#64748b",
    fontSize: 13,
    marginTop: 4,
  },
  exampleCloseButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f1f5f9",
  },
  exampleIllustration: {
    height: 160,
    borderRadius: 16,
    marginVertical: 20,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#cbd5e1",
    backgroundColor: "#f8fafc",
  },
  exampleCornerTopLeft: {
    position: "absolute",
    left: 18,
    top: 18,
    width: 26,
    height: 26,
    borderLeftWidth: 3,
    borderTopWidth: 3,
    borderColor: "#15803d",
  },
  exampleCornerTopRight: {
    position: "absolute",
    right: 18,
    top: 18,
    width: 26,
    height: 26,
    borderRightWidth: 3,
    borderTopWidth: 3,
    borderColor: "#15803d",
  },
  exampleCornerBottomLeft: {
    position: "absolute",
    left: 18,
    bottom: 18,
    width: 26,
    height: 26,
    borderLeftWidth: 3,
    borderBottomWidth: 3,
    borderColor: "#15803d",
  },
  exampleCornerBottomRight: {
    position: "absolute",
    right: 18,
    bottom: 18,
    width: 26,
    height: 26,
    borderRightWidth: 3,
    borderBottomWidth: 3,
    borderColor: "#15803d",
  },
  exampleTips: {
    gap: 11,
  },
  exampleTipRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 9,
  },
  exampleTipText: {
    flex: 1,
    color: "#334155",
    fontSize: 13,
    lineHeight: 19,
  },
  exampleDoneButton: {
    minHeight: 48,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
    backgroundColor: "#f97316",
  },
  exampleDoneButtonText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "900",
  },
  refreshText: {
    fontSize: 13,
    color: "#f97316",
    fontWeight: "800",
  },
});
